[package]
name = "binance-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
csv = "1.3.1"
indicatif = "0.18.0"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
